YES = "Y"
NO = "N"
SYSTEM = "SYSTEM"
NOT_FOUND = "Not Found"

STATUS_SUCCESS = "Success"
STATUS_FAILED = "Failed"
STATUS_SUCCESS_UPDATE = "Data Updated Successfully"
STATUS_SUCCESS_DELETE = "Data Deleted Successfully"

VALIDATION_ERROR_NAME = "Name is required"
VALIDATION_ERROR_USERNAME = "Username is required"

ACCESS_TOKEN_EXPIRE_MINUTES = 15  # Access token expiry time
REFRESH_TOKEN_EXPIRE_DAYS = 7     # Refresh token expiry time

HTTP_SUCCESS = 200
HTTP_CREATED = 201
HTTP_ACCEPTED = 202
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500