FROM python:3.10.11-alpine

WORKDIR /app

COPY . .

#delete .env

# RUN rm .env

# RUN rm -rf venv

# RUN rm -rf __py_cache__

RUN pip install uv

RUN uv pip install --system -r requirements.txt

CMD [ "python", "main.py" ] 