LOGGING:
   version: 1
   formatters:
       stdout1:
          format: "%(asctime)s|%(levelname)s|%(module)s|%(funcName)s|%(lineno)d =>> %(message)s"
          datefmt: "%d.%m.%Y %H:%M:%S"
       outfile:
          format: "%(asctime)s|%(levelname)s|%(module)s|%(name)s|%(funcName)s|%(lineno)d =>> %(message)s"
          datefmt: "%Y.%m.%d %H:%M:%S"
   handlers:
       console1:
          formatter: stdout1
          class: logging.StreamHandler
          level: DEBUG
       fileoutrotate:
          class: logging.handlers.RotatingFileHandler
          level: DEBUG
          formatter: outfile
          filename: "logs/All.log"
          maxBytes: 10485760
          backupCount: 10
          encoding: utf8